version: "3.8"
services:
  web:
    build: .
    ports:
      - 3000:4000
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://db/images
    volumes:
      - .:/app
    depends_on:
      - db
    command: ./docker-entrypoint.sh
  db:
    image: mongo:4.0.28-xenial
    ports:
      - 27018:27017
    volumes:
      - storage:/data/db

volumes:
  storage:
